# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'load_prepare_file.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(843, 337)
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 800, 301))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"background-color: rgb(255, 255, 221);\n"
"border-color: rgb(0, 0, 255);")
        self.groupBox.setObjectName("groupBox")
        self.lbl_1 = QtWidgets.QLabel(self.groupBox)
        self.lbl_1.setGeometry(QtCore.QRect(230, 40, 341, 21))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.lbl_1.setFont(font)
        self.lbl_1.setObjectName("lbl_1")
        self.led_1 = QtWidgets.QLineEdit(self.groupBox)
        self.led_1.setGeometry(QtCore.QRect(30, 80, 471, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.led_1.setFont(font)
        self.led_1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.led_1.setObjectName("led_1")
        self.btn_1 = QtWidgets.QPushButton(self.groupBox)
        self.btn_1.setGeometry(QtCore.QRect(530, 80, 231, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_1.setFont(font)
        self.btn_1.setStyleSheet("background-color: rgb(170, 255, 0);\n"
"background-color: rgb(169, 170, 148);")
        self.btn_1.setObjectName("btn_1")
        self.led_2 = QtWidgets.QLineEdit(self.groupBox)
        self.led_2.setGeometry(QtCore.QRect(30, 170, 471, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.led_2.setFont(font)
        self.led_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.led_2.setObjectName("led_2")
        self.lbl_2 = QtWidgets.QLabel(self.groupBox)
        self.lbl_2.setGeometry(QtCore.QRect(100, 140, 341, 21))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.lbl_2.setFont(font)
        self.lbl_2.setStyleSheet("border-color: rgb(0, 0, 255);")
        self.lbl_2.setText("")
        self.lbl_2.setObjectName("lbl_2")
        self.led_3 = QtWidgets.QLineEdit(self.groupBox)
        self.led_3.setGeometry(QtCore.QRect(160, 240, 471, 31))
        self.led_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.led_3.setAlignment(QtCore.Qt.AlignCenter)
        self.led_3.setObjectName("led_3")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(10, 550, 761, 21))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.action_4 = QtWidgets.QAction(MainWindow)
        self.action_4.setObjectName("action_4")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "KL Analyses skript"))
        self.groupBox.setTitle(_translate("MainWindow", "Выбор Excel-файла с информацией о реализованных Лотах"))
        self.lbl_1.setText(_translate("MainWindow", "Выберите Excel-файл"))
        self.btn_1.setText(_translate("MainWindow", "Кнопка выбора файла"))
        self.action.setText(_translate("MainWindow", "Новый"))
        self.action_2.setText(_translate("MainWindow", "Открыть"))
        self.action_3.setText(_translate("MainWindow", "Сохранить"))
        self.action_4.setText(_translate("MainWindow", "Выход"))
